percent-time: 60 # раз в сколько минут будет происходить начисление процентов

messages:
  add-bank-money: '&fВы &aуспешно&f положили &e%money%руб.&f в банк &r%bank_name%&f'
  take-bank-money: '&fВы &aуспешно&f сняли &e%money%руб.&f С уважением, Ваш &r%bank_name%&f'
  bank-register: '&fВы зарегистрировались в банке &r%bank_name%'
  bank-register-admin: '&fВы зарегистрировали&e %player%&f в банке &r%bank_name%'
  percent-added: '&fВам начислено &6%percent%&f на ваш вклад в банке &r%bank_name%&f, теперь его сумма составит: &a%money%руб.'
  no-perm: '&cСИСТЕМА БАНКОВ | У Вас нет прав.'

commands:
  help-msg:
    - ''
    - '&6&lСИСТЕМА БАНКОВ &7| &e&lRUSBANK'
    - '&e/bank add (название банка) (кол-во денег)&f | положить деньги на баланс в банке.'
    - '&e/bank take (название банка) (кол-во денег)&f | снять деньги с баланса банка.'
    - '&e/bank register (название банка)&f | зарегистрироватся в банке.'
    - '&e/bank balance (название банка)&f | проверить баланс банка.'
    - ''
  help-admin:
    - ''
    - '&6&lСИСТЕМА БАНКОВ (ADMIN) &7| &e&lRUSBANK'
    - '&e/bank add (ник) (название банка) (кол-во денег)&f | положить деньги на баланс игрока в банке.'
    - '&e/bank take (ник) (название банка) (кол-во денег)&f | снять деньги с баланса банка игрока.'
    - '&e/bank register (ник) (название банка)&f | зарегистрировать игрока в банке.'
    - '&e/bank check (ник) (название банка) &f| посмотреть баланс игрока в банке.'
    - ''